# Generated by Django 6.1 on 2026-08-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'مقال', 'verbose_name_plural': 'مقالات'},
        ),
    ]
