# Generated by Django 6.1 on 2026-08-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_order_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
