# Generated by Django 6.1 on 2026-08-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_order_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
