# Generated by Django 6.1 on 2026-08-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='عن الموقع', max_length=200, verbose_name='عنوان الصفحة')),
                ('description', models.TextField(verbose_name='من نحن؟')),
                ('our_mission', models.TextField(verbose_name='هدفنا')),
                ('what_we_offer', models.TextField(verbose_name='ماذا نقدم؟')),
            ],
        ),
        migrations.CreateModel(
            name='StudentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('review_text', models.TextField(verbose_name='رأي الطالب')),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.aboutpagecontent', verbose_name='صفحة عن الموقع')),
            ],
        ),
    ]
