# Generated by Django 6.1 on 2026-08-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_aboutpagecontent_studentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreview',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='صورة الطالب'),
        ),
        migrations.AddField(
            model_name='studentreview',
            name='student_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة أو التخصص (مثلا: السعودية)'),
        ),
    ]
