# Generated by Django 6.1 on 2026-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_studentreview_student_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'verbose_name': 'AboutPageContent', 'verbose_name_plural': 'AboutPageContents'},
        ),
        migrations.AlterField(
            model_name='studentreview',
            name='student_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة'),
        ),
    ]
