# Generated by Django 6.1 on 2026-08-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_aboutpagecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagecontent',
            options={'verbose_name': 'AboutPageContent', 'verbose_name_plural': 'About Page Contents'},
        ),
    ]
