# Generated by Django 6.1 on 2026-08-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_aboutpagecontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
